### ISSUE TITLE
Post new release

### ISSUE THREAD

**Issue by SuperQ** [mattn/go-xmlrpc#17]
It would be useful to tag a new release to include https://github.com/mattn/go-xmlrpc/pull/13.

**Comment by mattn** [comment]
Tagged v0.0.2

**Comment by SuperQ** [comment]
It looks like the same commit was tagged

**Comment by mattn** [comment]
Because nothing changed after #13

**Comment by SuperQ** [comment]
No, v0.0.2 is tagged to the same commit as v0.0.1. It's still `ac7d848`, not `b33132ba`.

**Comment by SuperQ** [comment]
![image](https://user-images.githubusercontent.com/1320667/67875138-3b1be380-fb36-11e9-8f08-6685b1c4ec63.png)

**Comment by mattn** [comment]
Yes, no updates from v0.0.1. v0.0.1 is tagged on last commit.

**Comment by mattn** [comment]
b33132ba is merge commit. Not real commit.

**Comment by SuperQ** [comment]
Yes, and that's important.

See the compare: https://github.com/mattn/go-xmlrpc/compare/v0.0.2...master

**Comment by mattn** [comment]
Updated v0.0.2

**Comment by SuperQ** [comment]
Sadly, updating in-place seems to break things due to Go caching. I think you will have to publish v0.0.3. :-(

**Comment by mattn** [comment]
Please try again.

**Comment by SuperQ** [comment]
:tada: https://github.com/prometheus/node_exporter/pull/1529 Thanks!
