### ISSUE TITLE
xml element not included in encoded response sent to server

### ISSUE THREAD

**Issue by lrstanley** [mattn/go-xmlrpc#7]
I noticed that this library isn't including the standard `<?xml [...]?>` element, which is required by many xmlrpc servers/other parsers. The xmlrpc spec doesn't define this as optional.

I've submitted PR https://github.com/mattn/go-xmlrpc/pull/6 which fixes this, as well as adds additional minor http improvements for those using this for highly concurrent environments.

**Comment by lrstanley** [comment]
also example, of how another library does it:
```
github.com/kolo/xmlrpc:
<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>your.method</methodName><params><param><value><string>somevalue</string></value></param><param><value><string>somevalue</string></value></param></params></methodCall>
```
```
github.com/mattn/go-xmlrpc:
<methodCall><methodName>your.method</methodName><params><param><value><string>somevalue</string></value></param><param><value><string>somevalue</string></value></param></params></methodCall>
```

**Comment by lrstanley** [comment]
PR https://github.com/mattn/go-xmlrpc/pull/6 has been merged, however I'll leave this open just in case there is anything else you'd like to get to in regards to your comments on the PR.

**Comment by mattn** [comment]
closed by https://github.com/mattn/go-xmlrpc/pull/6
